# Generated by Django 3.2.5 on 2021-07-22 00:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contacto', phone_field.models.PhoneField(blank=True, help_text='Teléfono de contacto', max_length=31)),
                ('direccion', models.TextField()),
            ],
        ),
    ]
