# Generated by Django 3.2.5 on 2021-07-23 20:12

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('apiempleados', '0002_auto_20210723_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='contacto',
            field=phone_field.models.PhoneField(blank=True, help_text='Teléfono de contacto', max_length=31),
        ),
    ]
